### ISSUE TITLE
Transfer timed out error.

### ISSUE THREAD

**Issue by awik32** [cmaion/polar#30]
Hi,

I got this error when SYNCing:

```
...
Downloading '/U/0/20210110/E/112046/00/RR.GZB' as '/home/aw/Polar/XXXXXXXX/U/0/20210110/E/112046/00/RR.GZB'
Traceback (most recent call last):
	30: from ./polar_ftp:64:in `<main>'
	29: from /home/aw/src/polar/lib/polar_ftp.rb:125:in `sync'
	28: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	27: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	26: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	25: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	24: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	23: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	22: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	21: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	20: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	19: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	18: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	17: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	16: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	15: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	14: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	13: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	12: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	11: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	10: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	 9: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	 8: from /home/aw/src/polar/lib/polar_ftp.rb:115:in `block in recurse'
	 7: from /home/aw/src/polar/lib/polar_ftp.rb:56:in `get'
	 6: from /home/aw/src/polar/lib/polar_usb_hid.rb:37:in `request'
	 5: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `read'
	 4: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `loop'
	 3: from /home/aw/src/polar/lib/polar_usb_hid.rb:46:in `block in read'
	 2: from /home/aw/src/polar/lib/polar_usb_hid.rb:110:in `usb_read'
	 1: from /var/lib/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/dev_handle.rb:465:in `interrupt_transfer'
/var/lib/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/dev_handle.rb:549:in `submit_transfer': error TRANSFER_TIMED_OUT (LIBUSB::ERROR_TIMEOUT)
```

When I retry the SYNC, I get this:
```
$ ./polar_ftp SYNC
Connected to Polar Loop 2 serial XXXXXXXX
Synchronizing to '/home/aw/Polar/XXXXXXXX'
Listing content of '/'
Traceback (most recent call last):
	8: from ./polar_ftp:64:in `<main>'
	7: from /home/aw/src/polar/lib/polar_ftp.rb:125:in `sync'
	6: from /home/aw/src/polar/lib/polar_ftp.rb:71:in `recurse'
	5: from /home/aw/src/polar/lib/polar_ftp.rb:33:in `dir'
	4: from /home/aw/src/polar/lib/polar_usb_hid.rb:37:in `request'
	3: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `read'
	2: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `loop'
	1: from /home/aw/src/polar/lib/polar_usb_hid.rb:68:in `block in read'
/home/aw/src/polar/lib/polar_usb.rb:113:in `process_error': Error: 175? (PolarUsb::PolarUsbError)
```

I reported this one before, but I did not mention that it was preceded by a "timeout".

-Albert.

**Comment by awik32** [comment]
Today, I got much the same, but the error pertains to another day (11th Jan instead of 10th):
```
Downloading '/U/0/20210111/E/083651/00/RR.GZB' as '/home/aw/Polar/XXXXXXXX/U/0/20210111/E/083651/00/RR.GZB'
Traceback (most recent call last):
	30: from ./polar_ftp:64:in `<main>'
	29: from /home/aw/src/polar/lib/polar_ftp.rb:125:in `sync'
	28: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	27: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	26: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	25: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	24: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	23: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	22: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	21: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	20: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	19: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	18: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	17: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	16: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	15: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	14: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	13: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	12: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	11: from /home/aw/src/polar/lib/polar_ftp.rb:75:in `block in recurse'
	10: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `recurse'
	 9: from /home/aw/src/polar/lib/polar_ftp.rb:72:in `each'
	 8: from /home/aw/src/polar/lib/polar_ftp.rb:115:in `block in recurse'
	 7: from /home/aw/src/polar/lib/polar_ftp.rb:56:in `get'
	 6: from /home/aw/src/polar/lib/polar_usb_hid.rb:37:in `request'
	 5: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `read'
	 4: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `loop'
	 3: from /home/aw/src/polar/lib/polar_usb_hid.rb:46:in `block in read'
	 2: from /home/aw/src/polar/lib/polar_usb_hid.rb:110:in `usb_read'
	 1: from /var/lib/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/dev_handle.rb:465:in `interrupt_transfer'
/var/lib/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/dev_handle.rb:549:in `submit_transfer': error TRANSFER_TIMED_OUT (LIBUSB::ERROR_TIMEOUT)
```

-aw

**Comment by cmaion** [comment]
No need to open a new issue.
As I said, could well be a USB cable/connection problem.
Recovery from aborted transfer is not bullet proof as I don't have access to the protocol specs.
I guess that retrying a few times to empty buffers / unplugging&plugging the USB cable may solve your issue.
