### ISSUE TITLE
ftp sync freeze (polar vantage v2)

### ISSUE THREAD

**Issue by kowalczuk** [cmaion/polar#35]
### my environment:
```sh
# polar vantage v2 (usb cables included with the watch)
# fresh (minimal) installation Ubuntu 21.10
> sudo apt install ruby-full
> sudo apt install git
> sudo apt-get install build-essential
> sudo apt install ruby-bundler
# clone repo
> sudo cp pkg/99-polar.rules /etc/udev/rules.d
> sudo udevadm control --reload-rules
> bundle install
```

### using:
```sh
> sudo chmod a+rw /dev/ttyACM0
> ruby polar_ftp SYNC
```
output freezing at ZH_JA.RAW:
```
...
Listing content of '/SYS/SPORT/3/'
Listing content of '/SYS/SPORT/2/'
Listing content of '/SYS/SPORT/1/'
Listing content of '/SYS/FONT/'
Downloading '/SYS/FONT/ZH_JA.RAW' as '/home/gamer/Polar/9461612B/SYS/FONT/ZH_JA.RAW'
```

**Comment by kowalczuk** [comment]
### windows 10
ruby 2.4.10p364 (2020-03-31 revision 67879) [i386-mingw32]

### using (PowerShell as admin):
```PowerShell
D:\polar-ruby> ruby .\polar_ftp --dev=//./COM4 GET /SYS/FONT/ZH_JA.RAW
```
output
```
Connected to ? serial ?
Downloading '/SYS/FONT/ZH_JA.RAW' as 'ZH_JA.RAW'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubyserial-0.6.0/lib/rubyserial/windows.rb:73:in `write': ERROR_SEM_TIMEOUT (RubySerial::Error)
        from D:/zdrowie/polar-ruby/lib/polar_usb_acm.rb:124:in `read'
        from D:/zdrowie/polar-ruby/lib/polar_usb_acm.rb:51:in `request'
        from D:/zdrowie/polar-ruby/lib/polar_ftp.rb:56:in `get'
        from ./polar_ftp:61:in `<main>'
```

### using (PowerShell as admin):
```PowerShell
D:\polar-ruby> ruby .\polar_ftp --dev=//./COM4 DIR /SYS/FONT
```
output:
```
Connected to ? serial ?
Listing content of '/SYS/FONT/'
   ZH_JA.RAW          5562936
```

**Comment by cmaion** [comment]
Hi

See https://github.com/cmaion/polar/issues/33 for a workaround

**Comment by kowalczuk** [comment]
Workaround works.
Sorry for duplicate issue.

**Comment by cmaion** [comment]
No worries.
I have added the workaround to my repository until I get the opportunity to reproduce the issue.
