### ISSUE TITLE
ERROR_SEM_TIMEOUT error always and for anything

### ISSUE THREAD

**Issue by sebastianzander** [cmaion/polar#42]
I am running Windows 10 with the latest Ruby version, in fact I just installed Ruby the first time and all dependencies should be up-to-date as well. I run your `polar` tool from an elevated PowerShell terminal, but no matter whether I request `DIR` or `SYNC` I always get such errors:

`$ ruby .\polar_ftp --dev=//./COM3 DIR /` results in:
```
Connected to ? serial ?
Synchronizing to 'C:/Users/live/Polar/unknown_serial'
Listing content of '/'
C:/Users/live/.local/share/gem/ruby/3.2.0/gems/rubyserial-0.6.0/lib/rubyserial/windows.rb:73:in `write': ERROR_SEM_TIMEOUT (RubySerial::Error)
        from D:/Development/Ruby/polar/lib/polar_usb_acm.rb:49:in `request'
        from D:/Development/Ruby/polar/lib/polar_ftp.rb:33:in `dir'
        from D:/Development/Ruby/polar/lib/polar_ftp.rb:71:in `recurse'
        from D:/Development/Ruby/polar/lib/polar_ftp.rb:129:in `sync'
        from ./polar_ftp:64:in `<main>'
```

I hardcoded the target directory since for some reason on my machine the device and serial are resolved as `?` and Windows could, of course, not create a directory with a question mark.

I was only twice able to get the directory listings for `/` and `/U/`. I then wanted to list `/U/0/` and since then I only received these semaphore function timeouts (ERROR_SEM_TIMEOUT). Any idea?

By the way: My ultimate goal was to extract more detailed GPS data from the watch, e.g. information about the precision of each recorded position. Not sure, however, whether Polar watches even record and/or store this information. Does anybody know this?

**Comment by cmaion** [comment]
Hi

Looks like an issue specific to Windows.
I just switched the serial port library used to another one (https://github.com/cmaion/polar/commit/2f0d717d39c94f93357f35723a02c9b4ece11a49). Pull and let me know if it works better for you!

As for precision of the GPS coordinates: the number of satellites used is recorded for each data point. Also time of first fix. See `polar_training2test` and dig into the `protobuf/` files.

**Comment by cmaion** [comment]
Hi

Just pushed a new commit, give it a try.

**Comment by sebastianzander** [comment]
Hey, only a little better. I can list some directories now, but I believe, the bigger the contents of the directory, the more unlikely it becomes that I can list its contents. But even if I could list the contents of e.g. `/U/0` in order to get my training sessions. I tried `GET /SYSCONF.BPB` (6 bytes? big), but then I get this error:

```
Connected to ? serial ?
Downloading '/SYSCONF.BPB' as 'SYSCONF.BPB'
D:/Development/Ruby/polar/lib/polar_usb_acm.rb:50:in `write': Invalid argument (Errno::EINVAL)
        from D:/Development/Ruby/polar/lib/polar_usb_acm.rb:50:in `request'
        from D:/Development/Ruby/polar/lib/polar_ftp.rb:56:in `get'
        from polar_ftp:61:in `<main>'
```

I found a tutorial from Microsoft about how to [Connect USB devices](https://learn.microsoft.com/en-us/windows/wsl/connect-usb) to Windows Subsystem for Linux. I will give it a try in the coming days.

**Comment by sebastianzander** [comment]
Using usbipd-win under Windows and linux-tools-generic and hwdata under Ubuntu (Windows Subsystem for Linux) I am now able to list directory contents and download files easily. Also everything is way faster; at least the directory listing which I am able to compare to running it under Windows directly.

However, I had to revert your last two commits. I guess you are better off with `rubyserial` after all.

**Comment by cmaion** [comment]
ok good to know.
I have pushed another commit that you may want to try too, both on Windows directly & WSL (force serial flow control to HARD -- if it doesn't work on Windows, you might try NONE to disable)
