### ISSUE TITLE
Ubuntu Ruby problems

### ISSUE THREAD

**Issue by mscottwvc** [cmaion/polar#43]
Havent used ruby before, but when I run 
`./polar_ftp DIR /`

I get:
```
/var/opt/hsh/polar/lib/protobuf/types_pb.rb:6:in `<top (required)>': undefined method `build' for #<Google::Protobuf::DescriptorPool:0x00005598a09655f8> (NoMethodError)
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/opt/hsh/polar/lib/polar_data_parser.rb:6:in `<top (required)>'
	from /var/opt/hsh/polar/lib/polar_ftp.rb:4:in `require_relative'
	from /var/opt/hsh/polar/lib/polar_ftp.rb:4:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ./polar_ftp:4:in `<main>'
```
Not sure how to fix this?
my gem list shows:
```
*** LOCAL GEMS ***

abbrev (default: 0.1.0)
base64 (default: 0.1.1)
benchmark (default: 0.2.0)
bigdecimal (default: 3.1.1)
bundler (default: 2.3.3)
bundler-unload (1.0.2)
cgi (default: 0.3.1)
csv (default: 3.2.2)
date (default: 3.2.2)
debug (1.4.0)
delegate (default: 0.2.0)
did_you_mean (default: 1.6.1)
digest (default: 3.1.0)
drb (default: 2.1.0)
english (default: 0.7.1)
erb (default: 2.2.3)
error_highlight (default: 0.3.0)
etc (default: 1.3.0)
executable-hooks (1.6.1)
fcntl (default: 1.0.1)
ffi (1.16.3)
fiddle (default: 1.1.0)
fileutils (default: 1.6.0)
find (default: 0.1.1)
forwardable (default: 1.3.2)
gem-wrappers (1.4.0)
getoptlong (default: 0.1.1)
google-protobuf (4.26.1 x86_64-linux)
io-console (default: 0.5.10)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.1)
ipaddr (default: 1.2.3)
irb (default: 1.4.1)
json (default: 2.6.1)
libusb (0.6.4 x86_64-linux)
logger (default: 1.5.0)
matrix (0.4.2)
minitest (5.15.0)
mutex_m (default: 0.1.1)
net-ftp (0.1.3)
net-http (default: 0.2.0)
net-imap (0.2.2)
net-pop (0.1.1)
net-protocol (default: 0.1.2)
net-smtp (0.3.1)
nkf (default: 0.1.1)
nokogiri (1.16.4 x86_64-linux)
observer (default: 0.1.1)
open-uri (default: 0.2.0)
open3 (default: 0.1.1)
openssl (default: 3.0.0)
optparse (default: 0.2.0)
ostruct (default: 0.5.2)
pathname (default: 0.2.0)
power_assert (2.0.1)
pp (default: 0.3.0)
prettyprint (default: 0.1.1)
prime (0.1.2)
pstore (default: 0.1.1)
psych (default: 4.0.3)
racc (1.7.3, default: 1.6.0)
rake (13.2.1, 13.0.6)
rbs (2.0.0)
rdoc (default: 6.4.0)
readline (default: 0.0.3)
readline-ext (default: 0.1.4)
reline (default: 0.3.0)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
rexml (3.2.5)
rinda (default: 0.1.1)
rss (0.2.9)
ruby2_keywords (default: 0.0.5)
rubygems-bundler (1.4.5)
rvm (1.11.3.9)
securerandom (default: 0.1.1)
serialport (1.3.2)
set (default: 1.0.2)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
stringio (default: 3.0.1)
strscan (default: 3.0.1)
syslog (default: 0.1.0)
tempfile (default: 0.1.2)
test-unit (3.5.3)
time (default: 0.2.0)
timeout (default: 0.2.0)
tmpdir (default: 0.1.2)
tsort (default: 0.1.0)
typeprof (0.21.1)
un (default: 0.2.0)
uri (default: 0.11.0)
weakref (default: 0.1.1)
yaml (default: 0.2.0)
zlib (default: 2.1.1)
```

**Comment by mscottwvc** [comment]
I get the same problem on Windows

**Comment by mscottwvc** [comment]
Got it fixed had to uninstall google-protobuf and install a lower version:
`gem install google-protobuf -v 3.25.1`
