### ISSUE TITLE
Install on Debian Bookworm

### ISSUE THREAD

**Issue by chri2** [cmaion/polar#46]
I tried to install and run on Debian Bookworm:

`bundle install` gives me 

```
$ bundle install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fetching gem metadata from https://rubygems.org/......
google-protobuf-3.17.3-x86_64-linux requires ruby version < 3.1.dev, >= 2.3, which is incompatible with the current
version, ruby 3.1.2p20
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
```

O.k. seems ruby is to new.

I tried to use `rbenv` and `ruby-build` to create a ruby environment for 3.0.4.

```
*** Following extensions are not compiled:
openssl:
        Could not be configured. It will not be installed.
        /tmp/ruby-build.20240805114556.33200.vTVJSv/ruby-3.0.4/ext/openssl/extconf.rb:113: OpenSSL >= 1.0.1, < 3.0.0 or LibreSSL >= 2.5.0 is required
        Check ext/openssl/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.

$ openssl version
OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)
```

For that my Debians openssl is too new.

Finally I started a Debian Buster using `distrobox` and have been able to run the software.

I'm not a ruby developer and know not much about how to setup ruby environments.

Is anybody still running the software - even on a modestly modern distribution? If so, how? Can someone help to generate a simple how-to to help Debian users to preserve the great functionality of this piece of code for the future?

**Comment by cmaion** [comment]
Hi,

I'm using ruby 3.3.4 on latest Ubuntu without any issue.
It should use google-protobuf 3.25.3, not sure why you are pulling 3.17.3.

**Comment by chri2** [comment]
Here's what I tried:

Cloned the repo into a new directory and changed to it. Then:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using bundler 2.3.15
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/3.1.0
  /var/lib/gems/3.1.0/build_info
  /var/lib/gems/3.1.0/cache
  /var/lib/gems/3.1.0/doc
  /var/lib/gems/3.1.0/extensions
  /var/lib/gems/3.1.0/gems
  /var/lib/gems/3.1.0/plugins
  /var/lib/gems/3.1.0/specifications
Fetching racc 1.8.1
Fetching google-protobuf 3.25.4 (x86_64-linux)
Fetching mini_portile2 2.8.7
Fetching ffi 1.17.0
Fetching serialport 1.3.2


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle config set --local path 'vendor/bundle'
      bundle install

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
sudo: Ein Passwort ist notwendig
```

Didn't provide a password and instead followed instruction:

```
$ bundle config set --local path ~/.local/lib/ruby
$ bundle install
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using bundler 2.3.15
Fetching google-protobuf 3.25.4 (x86_64-linux)
Fetching ffi 1.17.0
Fetching mini_portile2 2.8.7
Fetching serialport 1.3.2
Fetching racc 1.8.1
Installing serialport 1.3.2 with native extensions
Installing mini_portile2 2.8.7
Installing racc 1.8.1 with native extensions
Installing google-protobuf 3.25.4 (x86_64-linux)
Installing ffi 1.17.0 with native extensions
Fetching nokogiri 1.16.7 (x86_64-linux)
Installing nokogiri 1.16.7 (x86_64-linux)
Fetching libusb 0.7.1
Installing libusb 0.7.1 with native extensions
Bundle complete! 4 Gemfile dependencies, 8 gems now installed.
Bundled gems are installed into `/home/user/.local/lib/ruby`
$ ./polar_ftp 
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- libusb (LoadError)
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/cvogel/Source/polar-cmaion/polar/lib/polar_usb.rb:1:in `<top (required)>'
	from /home/cvogel/Source/polar-cmaion/polar/lib/polar_ftp.rb:3:in `require_relative'
	from /home/cvogel/Source/polar-cmaion/polar/lib/polar_ftp.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ./polar_ftp:4:in `<main>'
```

I do not exactly understan which file it is looking for, but there's libusb in two versions installed:

```
$ dpkg -L libusb-0.1-4 libusb-1.0-0
/.
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libusb-0.1.so.4.4.4
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libusb-0.1-4
/usr/share/doc/libusb-0.1-4/README.Debian
/usr/share/doc/libusb-0.1-4/changelog.Debian.gz
/usr/share/doc/libusb-0.1-4/changelog.gz
/usr/share/doc/libusb-0.1-4/copyright
/lib/x86_64-linux-gnu/libusb-0.1.so.4

/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libusb-1.0.so.0.3.0
/usr/share
/usr/share/doc
/usr/share/doc/libusb-1.0-0
/usr/share/doc/libusb-1.0-0/README
/usr/share/doc/libusb-1.0-0/changelog.Debian.gz
/usr/share/doc/libusb-1.0-0/changelog.gz
/usr/share/doc/libusb-1.0-0/copyright
/usr/lib/x86_64-linux-gnu/libusb-1.0.so.0
```

It used to work in Debian Buster, but I do not know why it doesn't anymore in Bookworm.

**Comment by paulkamer** [comment]
@chri2 I had to install `libusb-1.0-0-dev` as well to get it to work.
