### ISSUE TITLE
Poler Pacer on COM15 gets no connection

### ISSUE THREAD

**Issue by SvenLock** [cmaion/polar#51]
Thank you for providing the download tool!

I'm trying to get polarftp running on Windows. As you recommend I try to get connection to a PolarPacer through the comport (in this case COM15) with:

C:\Ablage\PolarPacer\polar-master>ruby polar_ftp  -dCOM15 DIR /

but I get a load error concerning the comport:

<internal:C:/Prg/Ruby33/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:
in `require': cannot load such file -- serialport (LoadError)
        from <internal:C:/Prg/Ruby33/lib/ruby/3.3.0/rubygems/core_ext/kernel_req
uire.rb>:136:in `require'
        from C:/Ablage/PolarPacer/polar-master/lib/polar_usb_acm.rb:1:in `<top (
required)>'
        from C:/Ablage/PolarPacer/polar-master/lib/polar_usb.rb:120:in `require_
relative'
        from C:/Ablage/PolarPacer/polar-master/lib/polar_usb.rb:120:in `<top (re
quired)>'
        from C:/Ablage/PolarPacer/polar-master/lib/polar_ftp.rb:3:in `require_re
lative'
        from C:/Ablage/PolarPacer/polar-master/lib/polar_ftp.rb:3:in `<top (requ
ired)>'
        from <internal:C:/Prg/Ruby33/lib/ruby/3.3.0/rubygems/core_ext/kernel_req
uire.rb>:136:in `require'
        from <internal:C:/Prg/Ruby33/lib/ruby/3.3.0/rubygems/core_ext/kernel_req
uire.rb>:136:in `require'
        from polar_ftp:4:in `<main>'

Do you have any idea to move on here?

Thanks a lot!

BR,
Sven

**Comment by cmaion** [comment]
Hi,

Did you run `bundle install` to install required libraries?

**Comment by SvenLock** [comment]
Hi,

yes, that the prot:

C:\Ablage\PolarPacer\polar-master>bundle install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has bee
n deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)'
instead.
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using bundler 2.2.31
Using ffi 1.17.0 (x86-mingw32)
Using google-protobuf 3.25.5 (x86-mingw32)
Using libusb 0.7.1 (x86-mingw32)
Fetching racc 1.8.0
Installing racc 1.8.0 with native extensions
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/

and ridk install with:

|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,3] 1

MSYS2 seems to be unavailable
Verify integrity of msys2-x86_64-20221028.exe ... Failed
Download https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20221028.exe
  to C:\Users\sgoers\AppData\Local\Temp/msys2-x86_64-20221028.exe
Installation failed: 404 Not Found

Manually downloading and running MSYS2 leads to error "msys2-x86_64-20221028.exe is not a valid windows exe"

That's the ponit I stuck.

**Comment by SvenLock** [comment]
Now I managed to install MSYS2, but only base install.

But I think I need to install option 3, because make is not found during "gem install serialport".

Is that right?

**Comment by cmaion** [comment]
Hi
I haven't tested on Windows for a long while, looks like stuff have evolved a bit since then.
I have updated the dependencies, just to make sure everything is up to date. Pull and run `bundle install` again.

You may indeed need the development toolchain.

I gave a quick look at nokogiri (for XML support) dependency installation notes, and the [specify the following](https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries) for Windows:
```
ridk exec pacman -S mingw-w64-ucrt-x86_64-libxslt
gem install nokogiri --platform=ruby -- --use-system-libraries
```
Give it a try!
